import { ConfiguracionMetodo } from '../../domain/entities/receta.entity';

export const RECETAS_POR_DEFECTO = [
  {
    nombre: 'Aeropress',
    metodo: 'aeropress',
    ratio: '1:16',
    notas: 'Método estándar con estilo invertido',
    usuarioId: 'system',
    calificacion: 5,
    gramosCafe: 17,
    mililitrosAgua: 272,
    temperaturaAgua: 91,
    tiempoExtraccion: 150,
    esPublica: true,
    esPorDefecto: true,
    configuracion: {
      grind: 'Media-fina (como sal de mesa)',
      temperature: '90-92°C',
      base: {
        cafe_g: 17,
        agua_total_ml: 272,
      },
      total_time_seconds: 150,
      steps: [
        {
          step: 1,
          time_start: 0,
          time_end: 0,
          action: 'Coloca el filtro, enjuaga con agua caliente y añade el café',
          water_ml: 0,
          calculation: null,
          requiere_accion_manual: true,
        },
        {
          step: 2,
          time_start: 0,
          time_end: 10,
          action: 'Bloom: vierte agua caliente en círculos',
          water_ml: 34,
          calculation: 'cafe_g * 2',
          requiere_accion_manual: false,
        },
        {
          step: 3,
          time_start: 10,
          time_end: 15,
          action: 'Remueve 5 veces con la cuchara',
          water_ml: 0,
          calculation: null,
          requiere_accion_manual: false,
        },
        {
          step: 4,
          time_start: 15,
          time_end: 30,
          action: 'Vierte el resto del agua lentamente',
          water_ml: 238,
          calculation: 'agua_total_ml - (cafe_g * 2)',
          requiere_accion_manual: false,
        },
        {
          step: 5,
          time_start: 30,
          time_end: 90,
          action: 'Coloca el émbolo (sin presionar) y espera',
          water_ml: 0,
          calculation: null,
          requiere_accion_manual: false,
        },
        {
          step: 6,
          time_start: 90,
          time_end: 120,
          action:
            'Gira el Aeropress sobre la taza y presiona lentamente (30 seg)',
          water_ml: 0,
          calculation: null,
          requiere_accion_manual: false,
        },
        {
          step: 7,
          time_start: 120,
          time_end: 150,
          action: '¡Listo! Diluye si prefieres un café más suave',
          water_ml: 0,
          calculation: null,
          requiere_accion_manual: true,
        },
      ],
    } as ConfiguracionMetodo,
  },
  {
    nombre: 'Chemex',
    metodo: 'chemex',
    ratio: '1:16',
    notas: 'Método para 6 tazas, escalable',
    usuarioId: 'system',
    calificacion: 5,
    gramosCafe: 40,
    mililitrosAgua: 640,
    temperaturaAgua: 92,
    tiempoExtraccion: 240,
    esPublica: true,
    esPorDefecto: true,
    configuracion: {
      grind: 'Media-gruesa (como arena gruesa)',
      temperature: '91-93°C',
      base: {
        cafe_g: 40,
        agua_total_ml: 640,
      },
      total_time_seconds: 240,
      steps: [
        {
          step: 1,
          time_start: 0,
          time_end: 0,
          action: 'Enjuaga el filtro con agua caliente',
          water_ml: 0,
          calculation: null,
          requiere_accion_manual: true,
        },
        {
          step: 2,
          time_start: 0,
          time_end: 45,
          action: 'Bloom: vierte agua en círculos lentos',
          water_ml: 80,
          calculation: 'cafe_g * 2',
          requiere_accion_manual: false,
        },
        {
          step: 3,
          time_start: 45,
          time_end: 105,
          action: 'Primer vertido: hasta 60% del total',
          water_ml: 256,
          calculation: 'agua_total_ml * 0.4',
          requiere_accion_manual: false,
        },
        {
          step: 4,
          time_start: 105,
          time_end: 180,
          action: 'Segundo vertido: el resto del agua en espiral',
          water_ml: 256,
          calculation: 'agua_total_ml * 0.4',
          requiere_accion_manual: false,
        },
        {
          step: 5,
          time_start: 180,
          time_end: 240,
          action: 'Deja escurrir completamente',
          water_ml: 0,
          calculation: null,
          requiere_accion_manual: false,
        },
      ],
    } as ConfiguracionMetodo,
  },
  {
    nombre: 'V60',
    metodo: 'v60',
    ratio: '1:16',
    notas: 'Versión James Hoffmann para 1 taza',
    usuarioId: 'system',
    calificacion: 5,
    gramosCafe: 15,
    mililitrosAgua: 240,
    temperaturaAgua: 93,
    tiempoExtraccion: 150,
    esPublica: true,
    esPorDefecto: true,
    configuracion: {
      grind: 'Media (entre sal fina y arena)',
      temperature: '92-94°C',
      base: {
        cafe_g: 15,
        agua_total_ml: 240,
      },
      total_time_seconds: 150,
      steps: [
        {
          step: 1,
          time_start: 0,
          time_end: 0,
          action: 'Enjuaga el filtro y haz un hueco en el café',
          water_ml: 0,
          calculation: null,
          requiere_accion_manual: true,
        },
        {
          step: 2,
          time_start: 0,
          time_end: 45,
          action: 'Bloom: vierte en círculos suaves',
          water_ml: 30,
          calculation: 'cafe_g * 2',
          requiere_accion_manual: false,
        },
        {
          step: 3,
          time_start: 45,
          time_end: 120,
          action: 'Vierte el resto del agua en espiral continua (75 seg)',
          water_ml: 210,
          calculation: 'agua_total_ml - (cafe_g * 2)',
          requiere_accion_manual: false,
        },
        {
          step: 4,
          time_start: 120,
          time_end: 120,
          action: 'Remueve el borde con la cuchara',
          water_ml: 0,
          calculation: null,
          requiere_accion_manual: true,
        },
        {
          step: 5,
          time_start: 120,
          time_end: 150,
          action: 'Deja escurrir hasta la última gota',
          water_ml: 0,
          calculation: null,
          requiere_accion_manual: false,
        },
      ],
    } as ConfiguracionMetodo,
  },
  {
    nombre: 'Prensa Francesa',
    metodo: 'prensa_francesa',
    ratio: '1:16',
    notas: 'Método tradicional con inmersión completa',
    usuarioId: 'system',
    calificacion: 5,
    gramosCafe: 30,
    mililitrosAgua: 480,
    temperaturaAgua: 94,
    tiempoExtraccion: 240,
    esPublica: true,
    esPorDefecto: true,
    configuracion: {
      grind: 'Gruesa (como pan rallado)',
      temperature: '93-95°C',
      base: {
        cafe_g: 30,
        agua_total_ml: 480,
      },
      total_time_seconds: 240,
      steps: [
        {
          step: 1,
          time_start: 0,
          time_end: 0,
          action: 'Añade el café en la prensa',
          water_ml: 0,
          calculation: null,
          requiere_accion_manual: true,
        },
        {
          step: 2,
          time_start: 0,
          time_end: 30,
          action: 'Vierte la mitad del agua (bloom)',
          water_ml: 240,
          calculation: 'agua_total_ml * 0.5',
          requiere_accion_manual: false,
        },
        {
          step: 3,
          time_start: 30,
          time_end: 40,
          action: 'Remueve 10 segundos',
          water_ml: 0,
          calculation: null,
          requiere_accion_manual: false,
        },
        {
          step: 4,
          time_start: 40,
          time_end: 60,
          action: 'Vierte el resto del agua',
          water_ml: 240,
          calculation: 'agua_total_ml * 0.5',
          requiere_accion_manual: false,
        },
        {
          step: 5,
          time_start: 60,
          time_end: 60,
          action: 'Tapa sin presionar',
          water_ml: 0,
          calculation: null,
          requiere_accion_manual: true,
        },
        {
          step: 6,
          time_start: 60,
          time_end: 240,
          action: 'Espera la extracción completa (3 minutos)',
          water_ml: 0,
          calculation: null,
          requiere_accion_manual: false,
        },
        {
          step: 7,
          time_start: 240,
          time_end: 240,
          action: 'Presiona lentamente hasta el fondo',
          water_ml: 0,
          calculation: null,
          requiere_accion_manual: true,
        },
      ],
    } as ConfiguracionMetodo,
  },
];

